### ISSUE TITLE
Command to install pandoc binary

### ISSUE THREAD

**Issue by hadley** [craigcitro/r-travis#136]
RStudio provides pandoc binaries. These are useful if you want to check Rmd vignettes:

``` yaml
  # Install binary pandoc from Rstudio
  - export PATH="$HOME/pandoc:$PATH"
  - mkdir $HOME/pandoc
  - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
      -d $HOME/pandoc
  - chmod +x $HOME/pandoc/pandoc
  - pandoc --version
```

**Comment by jjmalina** [comment]
@jjallaire would it be possible to make different downloads for each platform binary? that zip is 110MB :(

**Comment by craigcitro** [comment]
@jjmalina are you worried about it in the context of travis, or just in general?

**Comment by jjmalina** [comment]
@craigcitro in general, but would certainly help in the context of travis. there are 6 platform binaries in that zip.

**Comment by craigcitro** [comment]
@jjmalina at least for travis, the plan is to get pandoc into a base image, so it shouldn't be a worry long-term.

**Comment by jjallaire** [comment]
Those binaries are originally intended for the RStudio build process and
for various reasons it makes sense for us to have them all contained in a
single binary. You are of course are more than welcome to fork off one or
more of these into their own download though.
