### ISSUE TITLE
No R version information

### ISSUE THREAD

**Issue by vspinu** [craigcitro/r-travis#144]
Thanks Craig for this tool. Great job!

I am probably confused of how it should work, but I don't see session info or even R version anywere. Here is an [example](https://travis-ci.org/hadley/lubridate/builds/48869028) with `lubridate`. 

BTW, there are multiple `find: cannot search ': No such file or directory` in log dump. Not sure if that's the problem.

**Comment by craigcitro** [comment]
hey vitalie,

so there are two ways to find the version information:

1. if you dig through the logs, you can spot which version of the R deb gets installed. in your case, it [looks like 3.1.2](https://travis-ci.org/hadley/lubridate/builds/48869028#L401). this is admittedly a sub-par way to find this information out. ;)

2. there's also the `dump_sysinfo` command, which you can use to get a [handful of useful info](https://github.com/craigcitro/r-travis/blob/master/scripts/travis-tool.sh#L232) about your R session. currently you have to add a line using this to your `.travis.yml`, but maybe i should just do that automatically?

(closing for now, but feel free to reopen if those don't work, or you need different info those don't provide.)

**Comment by vspinu** [comment]
Thanks Craig. I searched for the apt-get part but missed it. `dump_sysinfo` works fine with the exception that it  is too long as because of the [wrapped lines](https://travis-ci.org/hadley/lubridate/builds/48906238#L747). Maybe you should add `options(width=400)` before `dump_sysinfo`.

**Comment by craigcitro** [comment]
bumping the width isn't a bad idea, but i don't know how the travis viewer does with wide lines. (or what the effective width of the tty this is going to is ...)

lemme give it a try.

**Comment by craigcitro** [comment]
even `400` isn't nearly enough for the whole contents; is this more readable? https://travis-ci.org/craigcitro/r-travis/jobs/48908381

**Comment by vspinu** [comment]
>  is this more readable? 

Hm. Actually not. The previous version is better. Travis wraps long lines and that makes it less convenient.

**Comment by craigcitro** [comment]
yeah, i was thinking the same. does `devtools::session_info` do better? giving it a shot:
  https://travis-ci.org/craigcitro/r-travis/jobs/48928280#L3091-L3104

**Comment by vspinu** [comment]
Yes. It's much more parsimonious and to the point. 

You can add `dump_devtools_sysinfo` job so that people could choose.  Also the command `R -q -e "devtools::session_info()"` gives a cleaner output.

**Comment by craigcitro** [comment]
i agree it's the right format -- but unfortunately it only shows *loaded* packages, not *all* packages. hmm.

**Comment by vspinu** [comment]
Ideally it should report packages loaded by the test suite. Would it be feassable to capture the output of `system_info` at the end of `run_tests`? This of course makes it impossible to use it before `run_tests` is triggered.  Not a big deal, I guess, as this info is useful mostly on test failures.
