### ISSUE TITLE
BOOTSTRAP_PANDOC doesn't install templates?

### ISSUE THREAD

**Issue by cboettig** [craigcitro/r-travis#145]
Vignettes are failing to build for me if I don't first pull down pandoc templates in addition to setting `BOOTSTRAP_PANDOC=1`.  Are the templates really not being installed or am I missing something?  

e.g. Here Travis fails due to missing templates: https://travis-ci.org/ropensci/rfishbase/builds/51016066
Adding the template (e.g. adding `mkdir -p ~/.pandoc/ && git clone https://github.com/jgm/pandoc-templates ~/.pandoc/templates` to `before_install` seems to fix this.

**Comment by craigcitro** [comment]
we definitely *don't* install the pandoc templates, but i suspect we *should*. this one's an easy fix (and well-timed -- I can do the same in our travis PR).

just to check -- @jjallaire, do you guys manually install the templates alongside pandoc? (are there other bits we should be including other than the templates?)

**Comment by jjallaire** [comment]
The pandoc templates are actually embedded into the standalone pandoc
executable. However, there was a period of time where this wan't happening
in our build configuration. If you get the very latest pandoc this should
be resolved: https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.13.1.zip

**Comment by craigcitro** [comment]
score -- thanks @jjallaire!

PR coming in a sec.
