### ISSUE TITLE
R .pkg link for Mac is outdated.

### ISSUE THREAD

**Issue by siddharthab** [craigcitro/r-travis#155]
Not sure if this is where it should be solved.

The .pkg link for R used by the script is http://cran.rstudio.com/bin/macosx/R-latest.pkg. This version actually points to 3.1.3 instead of 3.2.0. My guess is that they are still catering to Snow Leopard builds for their '-latest' link. Should we change the install link in the script to 3.2.0 instead of latest? Travis is definitely on something better than Snow Leopard.

**Comment by craigcitro** [comment]
@hadley or @eddelbuettel -- do you know who owns/updates that link?

**Comment by hadley** [comment]
That's @s-u

**Comment by s-u** [comment]
/me nods
now fixed

**Comment by craigcitro** [comment]
thanks @s-u!
