### ISSUE TITLE
Converting from r-travis: git config commands

### ISSUE THREAD

**Issue by jules32** [craigcitro/r-travis#159]
Hi there, 

I'm trying to convert my `.travis.yml` to r-travis, and am having problems with my `git config` commands. 

original
```
install:
- ./travis-tool.sh install_github ohi-science/rCharts
- ./travis-tool.sh install_github ohi-science/ohicore@dev
- git config --global user.email "xxx@email.com"
- git config --global user.name "Xxx Xxxx"
```

with r-travis
```
r_github_packages:
- ohi-science/rCharts
- ohi-science/ohicore@dev

# but now I need a different header for the git config commands...
- git config --global user.email "xxx@email.com"
- git config --global user.name "Xxx Xxxx"


# ...or I get this error: 
Error: unexpected symbol in " tryCatch({   devtools::install_github(c("ohi-
science/rCharts", "ohi-science/ohicore@dev", "git config --global user.email "xxx"
Execution halted
Your build has been stopped.
```

Any guidance would be much appreciated!

**Comment by craigcitro** [comment]
hi @jules32,

you just need to move those into one of the other [sections](http://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle) of the travis build. in this case, i think `before_install` or `after_install` sounds like a winner?

**Comment by jules32** [comment]
Thanks so much @craigcitro--

`before_install` did the trick!

**Comment by craigcitro** [comment]
w00t!
