### ISSUE TITLE
install_deps uses apt-get and uninstalls needed packages.

### ISSUE THREAD

**Issue by dblodgett-usgs** [craigcitro/r-travis#161]
I was having a hard time getting rgdal working and tracked it down to the use of install_deps using apt-get to install r-cran-devtools r-cran-testthat. The error I kept getting was that gdal-config was missing, it turned out that libgdal-dev and libgdal1-dev among other things were being removed by the apt-get install of devtools and testthat. Maybe a simple fix to use install.packages instead of apt-get to install these?

See the chunk of log output below. [Full log here.](https://travis-ci.org/dblodgett-usgs/climates/builds/74053945) I'm not sure why libgdal-dev and other packages are being removed, but to work around this, I just used install_r for devtools and testthat and things worked. See my [.travis.yml](https://github.com/dblodgett-usgs/climates/blob/4d6114fcc2abe9ff658a1e0b1808927600b432f0/.travis.yml) for the full solution.

`+COMMAND=install_deps
+echo 'Running command: install_deps'
Running command: install_deps
+shift
+case $COMMAND in
+InstallDeps
+EnsureDevtools
+Rscript -e 'if (!("devtools" %in% rownames(installed.packages()))) q(status=1)'
+RBinaryInstall devtools testthat
+[[ -z 2 ]]
+[[ Linux != \L\i\n\u\x ]]
+[[ -n '' ]]
+echo 'Installing *binary* R packages: devtools testthat'
Installing *binary* R packages: devtools testthat
++echo devtools testthat
++tr '[:upper:]' '[:lower:]'
+r_packages='devtools testthat'
++for r_package in '${r_packages}'
++echo -n 'r-cran-devtools '
++for r_package in '${r_packages}'
++echo -n 'r-cran-testthat '
+r_debs='r-cran-devtools r-cran-testthat '
+AptGetInstall r-cran-devtools r-cran-testthat
+[[ Linux != \L\i\n\u\x ]]
+[[ '' == \r\-\c\r\a\n\-\d\e\v\t\o\o\l\s\ \r\-\c\r\a\n\-\t\e\s\t\t\h\a\t ]]
+echo 'Installing apt package(s) r-cran-devtools' r-cran-testthat
Installing apt package(s) r-cran-devtools r-cran-testthat
+Retry sudo apt-get install r-cran-devtools r-cran-testthat
+sudo apt-get install r-cran-devtools r-cran-testthat

Reading package lists... 0%

Reading package lists... 100%

Reading package lists... Done

Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       

Reading state information... 0%

Reading state information... 0%

Reading state information... Done

The following packages were automatically installed and are no longer required:
  libxerces-c-dev liblwgeom-2.1.5 libspatialite-dev libdapserver7 libgif-dev
  libhdf4-alt-dev libarmadillo2 libdap11 libgdal1h libepsilon0 libnetcdf-dev
  libxerces-c28 libfreexl1 libspatialite3 libspatialite5 uuid-dev
  libgeos-3.2.2 libhdf5-serial-dev libhdf4-0-alt libxerces-c3.1 libpoppler19
  libdapclient3
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libcurl3 libcurl4-openssl-dev libicu52 libxml2 libxml2-dev littler r-cran-bh
  r-cran-bitops r-cran-brew r-cran-curl r-cran-digest r-cran-evaluate
  r-cran-git2r r-cran-httr r-cran-jsonlite r-cran-magrittr r-cran-memoise
  r-cran-mime r-cran-pkgkitten r-cran-r6 r-cran-rcpp r-cran-rcurl
  r-cran-roxygen2 r-cran-rstudioapi r-cran-rversions r-cran-stringi
  r-cran-stringr r-cran-whisker r-cran-xml2
Suggested packages:
  libcurl3-dbg r-cran-getopt r-cran-inline
The following packages will be REMOVED:
  libcurl4-gnutls-dev libdap-dev libgdal-dev libgdal1-dev
The following NEW packages will be installed:
  libcurl4-openssl-dev libicu52 littler r-cran-bh r-cran-bitops r-cran-brew
  r-cran-curl r-cran-devtools r-cran-digest r-cran-evaluate r-cran-git2r
  r-cran-httr r-cran-jsonlite r-cran-magrittr r-cran-memoise r-cran-mime
  r-cran-pkgkitten r-cran-r6 r-cran-rcpp r-cran-rcurl r-cran-roxygen2
  r-cran-rstudioapi r-cran-rversions r-cran-stringi r-cran-stringr
  r-cran-testthat r-cran-whisker r-cran-xml2
The following packages will be upgraded:
  libcurl3 libxml2 libxml2-dev
3 upgraded, 28 newly installed, 4 to remove and 260 not upgraded.`

**Comment by craigcitro** [comment]
so i'm not at all sure on why `apt` is removing those packages -- my guess is that `libcurl4-openssl-dev` conflicts with `libcurl4-gnutls-dev`, and that the `libgdal` packages depend on the latter? @eddelbuettel might know how to ask apt to explain?

`travis-tool.sh` will only do a binary `devtools` install if it's not already there -- you can easily coerce it by adding a

    - ./travis-tool.sh install_r devtools

before your first `install_github` command, and everything will work.

one more aside: `install_r` and friends take multiple arguments, if you want to install several packages at once. (i see a long list in your `.travis.yml`.)

**Comment by dblodgett-usgs** [comment]
Ahhh, ok. Thanks for the suggestion and tip, I'm a bit of a noob with this stuff.

**Comment by craigcitro** [comment]
no sweat!

(i hope we get to a point where no one has to deal with bash, but we're not there yet. :grinning:)

closing for now -- feel free to reopen if you hit more trouble.

**Comment by dblodgett-usgs** [comment]
Right on, testing a fixed up travis.yml now. :+1: for all the great work on CI tools for R!!!
