### ISSUE TITLE
Install of rgdal causing build failures

### ISSUE THREAD

**Issue by jhollist** [craigcitro/r-travis#163]
@craigcitro Thanks for taking a look at this.

rgdal is causing build failures.  Used to work with this [.travis.yml](https://github.com/jhollist/quickmapr/blob/master/.travis.yml).

Entirely possible I'm messing something up/forgetting something in the yml.

**Comment by craigcitro** [comment]
so it looks like `r-cran-rgdal` is just *missing* from the c2d4u ppa. @jhollist or @sckott -- has rgdal been updated recently?

**Comment by craigcitro** [comment]
sweet -- so michael has fixed this at the root, things should be back up and running.

(reopen if not!)

**Comment by jhollist** [comment]
Cool!  Camping this weekend, but will confirm Monday.  Thanks for your help
tracking the issue down.

**Comment by sckott** [comment]
works for me :+1:
