### ISSUE TITLE
run-dontrun and run-donttest supported?

### ISSUE THREAD

**Issue by berndbischl** [craigcitro/r-travis#165]
Hi,

I would like to pass the above flags to R CMD check, so travis runs my longer running examples that CRAN does not like. I find this pretty important so my example code is not broken.

Is this supported? Otherwise: Feature request.

**Comment by craigcitro** [comment]
hey @berndbischl -- you should be able to just add this to `r_check_args` ([docs](https://docs.travis-ci.com/user/languages/r#Package-check-options)).

**Comment by berndbischl** [comment]
thx. we should have seen this ourselves....
closing
