### ISSUE TITLE
dpkg: error processing r-base-core (--configure): causing build error

### ISSUE THREAD

**Issue by jhpoelen** [craigcitro/r-travis#170]
Hi! 

I've been using the ```r-travis``` method to run R on travis for awhile now (> year). It's been working like a charm. However, for some reason, the build crapped out today (see https://travis-ci.org/ropensci/rglobi/builds/65928670).  Before jumping into it, I wanted to share the issue publicly, because I think that others (e.g. @sckott) are also experiencing the issue and might have a fix/workaround already.

snippet of build log:
```
update-alternatives: using /usr/bin/tclsh8.5 to provide /usr/bin/tclsh (tclsh) in auto mode.

Setting up tk8.5 (8.5.11-1) ...

update-alternatives: using /usr/bin/wish8.5 to provide /usr/bin/wish (wish) in auto mode.

Setting up r-base-core (3.2.3-3precise0) ...

Creating config file /etc/R/Renviron with new version

/var/lib/dpkg/info/r-base-core.postinst: 57: /var/lib/dpkg/info/r-base-core.postinst: mktexlsr: not found

dpkg: error processing r-base-core (--configure):

 subprocess installed post-installation script returned error exit status 127

Setting up liblzma-dev (5.1.1alpha+20110809-3) ...

dpkg: dependency problems prevent configuration of r-base-dev:

 r-base-dev depends on r-base-core (>= 3.2.3-3precise0); however:

  Package r-base-core is not configured yet.

dpkg: error processing r-base-dev (--configure):

 dependency problems - leaving unconfigured

dpkg: dependency problems prevent configuration of r-cran-boot:

 r-cran-boot depends on r-base-core (>= 3.2.1-2precise0); however:

  Package r-base-core is not configured yet.

 r-cran-boot depends on r-api-3; however:

  Package r-api-3 is not installed.
```

**Comment by craigcitro** [comment]
This looks like the same root failure as https://github.com/travis-ci/travis-ci/issues/5462#issuecomment-171674080 if I'm reading it right; I *think* everything is back to working again?

**Comment by eddelbuettel** [comment]
Yep.

**Comment by jimhester** [comment]
Yes this is fixed, @jhpoelen if you restart your build it should not produce this error anymore.

**Comment by jhpoelen** [comment]
I didn't see any of the reported errors after restarting the build. Thank you @craigcitro @eddelbuettel @jimhester for speedy replies.
