### ISSUE TITLE
Travis changed it's Precise builds and now vignette building fails

### ISSUE THREAD

**Issue by zkamvar** [craigcitro/r-travis#172]
This build failed all of a sudden: https://travis-ci.org/grunwaldlab/poppr/builds/107399219
The builds used to not fail: https://travis-ci.org/grunwaldlab/poppr/builds/104170589

Here are all the changes that happened... none to the vignettes: https://github.com/grunwaldlab/poppr/compare/9a9e3b242c10f4bd5567ad94de015b3773bdef1e...master

A lot of it has to do with simple error messages like:

fullpage.sty not found

and 

inconsolata.sty not found

I've attempted to fix these by installing extra tex packages or attempting to turn vignettes off, but to no avail. Anyone else having similar issues?

**Comment by craigcitro** [comment]
@jimhester didn't you just fix this for native travis builds? is that something we could easily backport here?

**Comment by jimhester** [comment]
@zkamvar is actually using native travis, this issue should really be at https://github.com/travis-ci/travis-ci/issues

You need to use `tlmgr install XXX` to install the packages you need, the best place to install them is the `before_install` section of your `.travis.yml`. The list of packages now installed by default on native R travis is https://github.com/yihui/ubuntu-bin/blob/master/TeXLive.pkgs

**Comment by zkamvar** [comment]
@jimhester, thanks! I'll try your suggestion and then open an issue there if it doesn't work.
