### ISSUE TITLE
Testthat tests fail ONLY in Travis

### ISSUE THREAD

**Issue by alexsanjoseph** [craigcitro/r-travis#175]
Tests fail while they run on Travis. This is my code.

``` {r}
log_data = read_adapter_log_file(system.file(file_path_adapter_log, package = "mtconnectR"), condition_names)
data("example_log_data")
expect_true(all.equal(log_data, example_log_data))

```

Travis output

```
  2. Failure (at test-dataExtraction.R#45): (unknown) ----------------------------
  all.equal(log_data, example_log_data) isn't true
```

The weird thing is that I created the example log data by saving a copy of the log data, so it should be identical. Sure enough, that is how it works in every other environment I have tested and the check passes(Windows 7 and OSX machine) but while in travis environment it find the two data.frames different.

Other tests work fine.

I have been banging my head against this for two days. The fact that R CMD check gives only the last 13 lines of output doesn't help either so some solution to that would be helpful as well.

Please suggest if I need to provide any more details
Thanks,

Alex

**Comment by alexsanjoseph** [comment]
Well. After so much time I figured out the issue was that I was using a timestamp conversion from a different time zone. When I was testing locally it worked because the data was created in the same timestamp as the one which the data was saved.

I guess the only way this could have been avoided is if there was better error messages in testhat and/or a way to see more than 13 lines of data. 

Sorry for the trouble. Please delete the issue if that's the norm

**Comment by craigcitro** [comment]
So it sounds like you got this worked out -- but just to ask, are you using this repo or the native (`language: R`) support in travis?

If it's this repo, I encourage you to migrate, and there we automatically dump the full log on failure.

If it's native R support, I'd be curious to know why full failure logs weren't dumped (and @jimhester probably would, too).

**Comment by alexsanjoseph** [comment]
I was using the native R support on travis.

Are full logs supposed to  be dumped in that case? I thought it was a limitation of R CMD Check from here: https://github.com/craigcitro/r-travis/issues/150

**Comment by craigcitro** [comment]
Ah, yes, I'd forgotten about that. So Travis is dumping all the logs that are there, it's just that the logs are getting abbreviated in the check step.

**Comment by alexsanjoseph** [comment]
Yes exactly. Because of this, it was a pain in the ass to debug. Finally figured it out inch by inch. Wish there was a workaround for that issue.
