### ISSUE TITLE
Install non-R dependencies 

### ISSUE THREAD

**Issue by sckott** [craigcitro/r-travis#66]
One of my packages requires the R package [rgdal](http://cran.r-project.org/web/packages/rgdal/index.html), which depends on a non-R library called [GDAL](http://trac.osgeo.org/gdal/wiki/DownloadSource). 

Does anyone else depend on `rgdal`? Perhaps there is a way to specify installing GDAL in the `.travis.yml` file?

**Comment by dblodgett-usgs** [comment]
In case anyone else gets here and is stumped, this package seems to have the ticket for getting this going: https://travis-ci.org/rOpenGov/fmi

**Comment by nuest** [comment]
In case anybody gets  here, still, the new Travis infrastructure supports installing system depdencies (no need for `travis-tool.sh`) with

``` yml
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
```

See https://docs.travis-ci.com/user/languages/r#APT-packages

**Comment by trosendal** [comment]
Tried the solution presented by @nuest and got the following error:

$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libgdal-dev libproj-dev
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libgdal-dev : Depends: libhdf5-serial-dev
E: Unable to correct problems, you have held broken packages.

**Comment by nuest** [comment]
There might be an issue with dependency resolution (".. have unmet dependencies"). See also https://github.com/ropensci/RNeXML/issues/61 and some suggestions here http://askubuntu.com/questions/206593/how-to-install-rgdal-on-ubuntu-12-10

Maybe try with `libgdal1-dev` first and see what happens?

**Comment by trosendal** [comment]
Same error... I'll read through the links you suggest. Thanks :)

$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libgdal1-dev libgdal-dev libproj-dev
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libgdal-dev : Depends: libhdf5-serial-dev
E: Unable to correct problems, you have held broken packages.

**Comment by trosendal** [comment]
@nuest I tried the solutions presented in the link that you suggested but always get dependency errors that I can't solve. The issue and project are here if anyone is interested: https://github.com/SVA-SE/svamap/issues/7
