### ISSUE TITLE
Detect and use packrat

### ISSUE THREAD

**Issue by hadley** [craigcitro/r-travis#7]
i.e. if `packrat.lock` found, run `packrat::restore()` instead of `install_deps`.  See https://github.com/rstudio/packrat

(More of a long-term idea than something immediate)

**Comment by benmarwick** [comment]
Can this be re-opened? I'm finding packrat to be quite stable and reliable, and now use it a lot when developing compendium packages. I'd love to know how to get Travis to use my packrat packages rather than downloading the CRAN versions.

**Comment by craigcitro** [comment]
worth chatting about, but let's do it over on a new Travis ticket. this repo is deprecated.

**Comment by benmarwick** [comment]
Thanks, I've made a post over at https://github.com/travis-ci/travis-ci/issues/6504
